@accessToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNvZ25pdG9Mb2NhbCJ9.eyJhdXRoX3RpbWUiOjE3NjQzOTI5MTcsImNsaWVudF9pZCI6ImV3MjB4dDViYzdhc3RhZXh5MXU3bXgzMXQiLCJldmVudF9pZCI6IjUzODYzZDBlLTEyMGUtNDQ0Ny1iNGFjLTMwYjc5Njc2ODIxNyIsImlhdCI6MTc2NDM5MjkxNywianRpIjoiYzhkMTg1NmItODVhOS00MzgxLTg3NmQtMTQxZjI1NTVlOTAxIiwic2NvcGUiOiJhd3MuY29nbml0by5zaWduaW4udXNlci5hZG1pbiIsInN1YiI6IjdlMDE2ODI5LTczNDYtNGIxMS1hMzdiLTY3YjVmMWE4ODBjMCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiN2UwMTY4MjktNzM0Ni00YjExLWEzN2ItNjdiNWYxYTg4MGMwIiwiZXhwIjoxNzY0Mzk2NTE3LCJpc3MiOiJodHRwOi8vMC4wLjAuMDo5MjI5L2xvY2FsXzN4MTJaYmxhIn0.SYO5fZA7iPmh3CgKZGN2YdqNNYBgLKrGUfFoIE3iEFEjD5WdHO9RfoAXMqPquJrOG0QxDQO_L_5BzmqFJ_RLc2al3Li9mnr6ohYa8eVDs6f2Oz-w1Oba2-uMQv8ip9VMuHHSg8__06sJwH4GI1WPTmlcdhaE0F8DiwsmKyXDWVWPGChv0B5vTVRHQptHAI-6NODzX0oQyh-T8XYTUrFZW-fYMbvVFPOEfKaz6Pfl-Sdy9Xa0hdk7qfUllNatPHeR_MbhivnGWDhoWQKGnofXjuZwWHToy4vvwkoiPYqL6mFAa30_F11z96Nr8DJkCaLkb1_cG9tv-2Qiiy81XPcKLA

###

GET http://localhost:4000/products

###

POST http://localhost:4000/products
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "product 1",
    "description": "info",
    "price": 99,
    "imageUrl": "http://localhost:4566/my-products-bucket/2fedd4c5-13eb-4276-b55e-fde77559c320-foto.jpg"
}


### Subir imagen a S3

POST http://localhost:4000/products/upload
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="foto.jpg"
Content-Type: image/jpeg

< ./Screenshot_1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
